scripts:
  - name: Clean workspace
    script: flutter clean
workflows:
  sendtalk-build:
    name: SendTalk Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      # Remove or comment out Analyze step
      # - name: Analyze code
      #   script: flutter analyze
      - name: Run tests
        script: flutter test || true
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
